=== feldob/InPUT/CodeMappings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Copyright (C) 2012 Felix Dobslaw$ Permission is hereby granted, free 
	of charge, to any person obtaining a copy of this software and associated 
	documentation files (the "Software"), to deal in the Software without restriction, 
	including without limitation the rights to use, copy, modify, merge, publish, 
	distribute, sublicense, and/or sell copies of the Software, and to permit 
	persons to whom the Software is furnished to do so, subject to the following 
	conditions: The above copyright notice and this permission notice shall be 
	included in all copies or substantial portions of the Software. THE SOFTWARE 
	IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
	BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
	PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS 
	BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
	OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH 
	THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. -->
<xsd:schema targetNamespace="http://TheInPUT.org/CodeMappings"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:m="http://TheInPUT.org/DesignSpace" xmlns:i="http://TheInPUT.org/CodeMappings">
	<xsd:import namespace="http://TheInPUT.org/DesignSpace"
		schemaLocation="DesignSpace.xsd" />

	<xsd:element name="CodeMappings" type="i:dslType" />

	<xsd:complexType name="dslType">
		<xsd:sequence maxOccurs="1" minOccurs="0">
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="MappingType" type="i:mapType" />
			</xsd:sequence>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="Mapping" type="i:mapType" />
			</xsd:sequence>
		</xsd:sequence>
		<xsd:attributeGroup ref="m:idAttributes" />
		<xsd:attribute name="type" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="mapType">
		<xsd:sequence maxOccurs="1" minOccurs="0">
			<xsd:choice>
				<xsd:element name="Wrapper" type="i:wrapType" />
				<xsd:element name="Complex" type="i:complexType" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attributeGroup ref="m:idAttributes" />
		<xsd:attribute name="type" type="xsd:string" />
		<xsd:attribute name="get" type="xsd:string" />
		<xsd:attribute name="set" type="xsd:string" />
		<xsd:attribute name="constructor" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="complexType">
		<xsd:attribute name="type" type="xsd:string" use="required" />
		<xsd:attribute name="add" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="wrapType">
		<xsd:attribute name="type" type="xsd:string" use="required" />
		<xsd:attribute name="get" type="xsd:string" />
		<xsd:attribute name="set" type="xsd:string" />
		<xsd:attribute name="constructor" type="xsd:string" />
	</xsd:complexType>
</xsd:schema>

=== feldob/InPUT/Java/src/DatabaseTransactionExamples/structuredMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:CodeMappings id="structured" xmlns:i="http://TheInPUT.org/CodeMappings" xmlns:i1="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://TheInPUT.org/CodeMappings http://TheInPUT.org/CodeMappings.xsd ">
<i:Mapping id="Decision" type="se.miun.itm.input.example.structured.model.Decision"/>
<i:Mapping id="Decision.FirstChoice" type="se.miun.itm.input.example.structured.model.FirstChoice"/>
<i:Mapping id="Decision.SecondChoice" type="se.miun.itm.input.example.structured.model.SecondChoice"/>
<i:Mapping id="Decision.ThirdChoice" type="se.miun.itm.input.example.structured.model.ThirdChoice"/>

<i:Mapping id="AnotherDecision" type="se.miun.itm.input.example.structured.model.AnotherDecision"/>
<i:Mapping id="AnotherDecision.Raw" type="se.miun.itm.input.example.structured.model.Raw"/>
<i:Mapping id="AnotherDecision.Medium" type="se.miun.itm.input.example.structured.model.Medium"/>
<i:Mapping id="AnotherDecision.WellDone" type="se.miun.itm.input.example.structured.model.WellDone"/>
</i:CodeMappings>

=== feldob/InPUT/Java/src/Tuning_Test/combinedSpaceMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:CodeMappings id="combined" xmlns:i="http://TheInPUT.org/CodeMappings"
	xmlns:i1="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://TheInPUT.org/CodeMappings http://theinput.org/CodeMappings.xsd ">
	<i:Mapping id="SomeStructuralParent" type="model.SomeStructuralParent"
		constructor="SomeSharedPrimitiveSub" />
	<i:Mapping id="SomeStructuralParent.YetAnotherFirstChoice"
		type="model.YetAnotherFirstChoice" />
	<i:Mapping id="SomeStructuralParent.YetAnotherSecondChoice"
		type="model.YetAnotherSecondChoice" constructor="" />
	<i:Mapping id="SomeStructuralParent.YetAnotherThirdChoice"
		type="model.YetAnotherThirdChoice" constructor="SomeSharedPrimitiveSub SomeChoiceSpecificPrimitiveSub" />
	<i:Mapping id="SomeIrrelevantParameter" type="model.SomeStructuralParent"
		constructor="SomeSharedPrimitiveSub" />
	<i:Mapping id="AnotherStructural" type="model.AnotherStructural" />
	<i:Mapping id="AnotherStructural.AnotherFirstChoice" type="FIRST" />

	<i:Mapping id="SomeComplexStructural" type="model.SomeAbstractComplexStructural">
		<i:Complex type="model.SomeComplexStructural" add="addEntry" />
	</i:Mapping>
	<i:Mapping id="SomeComplexStructural.FirstChoice" type="model.SingleComplexChoice" constructor="A" />
	<i:Mapping id="SomeComplexStructural.SecondChoice" type="model.SingleComplexChoice" />
	
	<i:Mapping id="SomeFixedSingleArrayStructural" type="model.SomeAbstractComplexStructural"/>
	<i:Mapping id="SomeFixedSingleArrayStructural.FirstChoice" type="model.SingleComplexChoice" constructor="A" />
	<i:Mapping id="SomeFixedSingleArrayStructural.SecondChoice" type="model.SingleComplexChoice" />
</i:CodeMappings>

=== feldob/InPUT/Java/Source/Tuning_Test/structuralSpaceMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:CodeMappings id="structural" xmlns:i="http://TheInPUT.org/CodeMappings"
	xmlns:i1="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://TheInPUT.org/CodeMappings http://theinput.org/CodeMappings.xsd ">
	
	<i:Mapping id="SomeStructural" type="model.SomeStructural" />
	<i:Mapping id="SomeStructural.FirstChoice" type="model.SomeFirstChoice" />
	<i:Mapping id="SomeStructural.SecondChoice" type="model.SomeSecondChoice" />
	<i:Mapping id="SomeStructural.ThirdChoice" type="model.SomeThirdChoice" />
	
	
		<i:Mapping id="SomeStructuralParent" type="model.SomeStructuralParent"
		constructor="SomeSharedPrimitiveSub" />
	<i:Mapping id="SomeStructuralParent.YetAnotherFirstChoice"
		type="model.YetAnotherFirstChoice" />
	<i:Mapping id="SomeStructuralParent.YetAnotherSecondChoice"
		type="model.YetAnotherSecondChoice" constructor="" />
	<i:Mapping id="SomeStructuralParent.YetAnotherThirdChoice"
		type="model.YetAnotherThirdChoice" constructor="SomeSharedPrimitiveSub SomeChoiceSpecificPrimitiveSub" />
		
</i:CodeMappings>

=== feldob/InPUT/Java/src/DatabaseTransactionExamples/structuredMappingAdvanced.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:CodeMappings id="structuredAdv" xmlns:i="http://TheInPUT.org/CodeMappings" xmlns:i1="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://TheInPUT.org/CodeMappings http://TheInPUT.org/CodeMappings.xsd ">
<i:Mapping id="Steak" type="se.miun.itm.input.example.structured.model.AnotherDecision"/>
<i:Mapping id="Steak.Raw" type="se.miun.itm.input.example.structured.model.Raw"/>
<i:Mapping id="Steak.Medium" type="se.miun.itm.input.example.structured.model.Medium"/>
<i:Mapping id="Steak.WellDone" type="se.miun.itm.input.example.structured.model.WellDone"/>

<i:Mapping id="Steak.Medium.Rather" type="se.miun.itm.input.example.structured.model.AnotherDecision"/>
<i:Mapping id="Steak.Medium.Rather.Raw" type="se.miun.itm.input.example.structured.model.Raw"/>
<i:Mapping id="Steak.Medium.Rather.WellDone" type="se.miun.itm.input.example.structured.model.WellDone"/>

</i:CodeMappings>

=== feldob/InPUT/Java/Source/Tests/testSpaceMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:CodeMappings id="testSpace" xmlns:i="http://TheInPUT.org/CodeMappings"
	xmlns:i1="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://TheInPUT.org/CodeMappings http://theinput.org/CodeMappings.xsd ">


	<i:Mapping id="SomeStructural" type="model.SomeStructural" />
	<i:Mapping id="SomeStructural.SomeFirstChoice" type="model.SomeFirstChoice" />
	<i:Mapping id="SomeStructural.SomeSecondChoice" type="model.SomeSecondChoice" />
	<i:Mapping id="SomeStructural.SomeThirdChoice" type="model.SomeThirdChoice" />


	<i:Mapping id="AnotherStructural" type="model.AnotherStructural" />
	<i:Mapping id="AnotherStructural.AnotherFirstChoice" type="FIRST" />
	<i:Mapping id="AnotherStructural.AnotherSecondChoice" type="SECOND" />
	<i:Mapping id="AnotherStructural.AnotherThirdChoice" type="THIRD" />


	<i:Mapping id="SomeStructuralParent" type="model.SomeStructuralParent"
		constructor="SomeSharedPrimitiveSub" />
	<i:Mapping id="SomeStructuralParent.YetAnotherFirstChoice"
		type="model.YetAnotherFirstChoice" />
	<i:Mapping id="SomeStructuralParent.YetAnotherSecondChoice"
		type="model.YetAnotherSecondChoice" constructor="" />
	<i:Mapping id="SomeStructuralParent.YetAnotherThirdChoice"
		type="model.YetAnotherThirdChoice" constructor="SomeSharedPrimitiveSub SomeChoiceSpecificPrimitiveSub" />

	<i:Mapping id="AnotherStructuralParent" type="model.AnotherStructuralParent"
		constructor="SomeSharedStructuralSub" />
	<i:Mapping id="AnotherStructuralParent.SomeSharedStructuralSub"
		type="model.SomeSharedStructuralSub" />
	<i:Mapping
		id="AnotherStructuralParent.SomeSharedStructuralSub.SomeSubChoice"
		type="model.SomeSubChoice" />
	<i:Mapping
		id="AnotherStructuralParent.SomeSharedStructuralSub.AnotherSubChoice"
		type="model.AnotherSubChoice" />

	<i:Mapping id="AnotherStructuralParent.AndYetAnotherFirstChoice"
		type="model.AndYetAnotherFirstChoice" />
	<i:Mapping id="AnotherStructuralParent.AndYetAnotherSecondChoice"
		type="model.AndYetAnotherSecondChoice" constructor="SomeSharedStructuralSub SomeChoiceSpecificStructuralSub" />
	<i:Mapping
		id="AnotherStructuralParent.AndYetAnotherSecondChoice.SomeChoiceSpecificStructuralSub"
		type="model.SomeChoiceSpecificStructuralSub" />
	<i:Mapping
		id="AnotherStructuralParent.AndYetAnotherSecondChoice.SomeChoiceSpecificStructuralSub.AlsoSingleChoicesAreValid"
		type="model.AlsoSingleChoicesAreValid" />

	<i:Mapping id="SomeStructuralArrayOfUnspecifiedSize" type="model.SomeStructural" />
	<i:Mapping id="SomeStructuralArrayOfUnspecifiedSize.FirstChoice"
		type="model.SomeFirstChoice" />
	<i:Mapping id="SomeStructuralArrayOfUnspecifiedSize.SecondChoice"
		type="model.SomeSecondChoice" />

	<i:Mapping id="CustomizableInputDemonstrator" type="model.SomeCommonStructural" />
	<i:Mapping id="CustomizableInputDemonstrator.WrappedPrimitive" get="toValue">
		<i:Wrapper type="model.Wrapper" get="getPrimitive"
			set="setPrimitive" />
	</i:Mapping>
	<i:Mapping id="CustomizableInputDemonstrator.CustomizableSetGetPrimitive"
		set="customizableSetter" get="andTheCustomizableGetter" />
	<i:Mapping id="CustomizableInputDemonstrator.FirstChoice"
		type="model.SomeFirstChoice" />
	<i:Mapping id="CustomizableInputDemonstrator.SecondChoice"
		type="model.SomeSecondChoice" />
		
		<i:Mapping id="SomeComplexStructural" type="model.SomeAbstractComplexStructural">
			<i:Complex type="model.SomeComplexStructural" add="addEntry"/>
		</i:Mapping>
	<i:Mapping id="SomeComplexStructural.TheSingleChoice"
		type="model.SingleComplexChoice" />
	<i:Mapping id="SomeComplexStructural.TheSecondSingleChoice"
		type="model.SecondSingleComplexChoice" />

</i:CodeMappings>
