=== feldob/InPUT/DesignSpace.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Copyright (C) 2012 Felix Dobslaw$ Permission is hereby granted, free 
	of charge, to any person obtaining a copy of this software and associated 
	documentation files (the "Software"), to deal in the Software without restriction, 
	including without limitation the rights to use, copy, modify, merge, publish, 
	distribute, sublicense, and/or sell copies of the Software, and to permit 
	persons to whom the Software is furnished to do so, subject to the following 
	conditions: The above copyright notice and this permission notice shall be 
	included in all copies or substantial portions of the Software. THE SOFTWARE 
	IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
	BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
	PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS 
	BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
	OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH 
	THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. -->

<xsd:schema targetNamespace="http://TheInPUT.org/DesignSpace"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:i="http://TheInPUT.org/DesignSpace">

	<xsd:element name="DesignSpace" type="i:designSpaceType" />
	<xsd:complexType name="designSpaceType">
		<xsd:sequence>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="SChoiceType" type="i:structChoiceType" />
			</xsd:sequence>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:choice>
					<xsd:element name="SParam" type="i:complexParamType" />
					<xsd:element name="NParam" type="i:numericType" />
				</xsd:choice>
			</xsd:sequence>
		</xsd:sequence>
		<xsd:attributeGroup ref="i:idAttributes" />
		<xsd:attribute name="mapping" type="xsd:string" />
	</xsd:complexType>
	<xsd:complexType name="complexParamType">
		<xsd:sequence maxOccurs="1" minOccurs="1">
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:choice>
					<xsd:element name="SChoice" type="i:structChoiceType" />
					<xsd:element name="SParam" type="i:complexParamType" />
					<xsd:element name="NParam" type="i:numericType" />
				</xsd:choice>
			</xsd:sequence>
		</xsd:sequence>
		<xsd:attributeGroup ref="i:idAttributes" />
		<xsd:attribute name="type" type="xsd:string" />
		<xsd:attribute name="fixed" type="xsd:string" />
		<xsd:attribute name="optional" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="structChoiceType">
		<xsd:sequence>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:choice>
					<xsd:element name="SParam" type="i:complexParamType" />
					<xsd:element name="NParam" type="i:numericType" />
				</xsd:choice>
			</xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="type" type="xsd:string" />
		<xsd:attributeGroup ref="i:idAttributes" />
	</xsd:complexType>

	<xsd:complexType name="numericType">
		<xsd:attribute name="inclMin" type="xsd:anySimpleType" />
		<xsd:attribute name="exclMin" type="xsd:anySimpleType" />
		<xsd:attribute name="inclMax" type="xsd:anySimpleType" />
		<xsd:attribute name="exclMax" type="xsd:anySimpleType" />
		<xsd:attribute name="fixed" type="xsd:string" />
		<xsd:attributeGroup ref="i:idAttributes" />
		<xsd:attribute name="type" type="xsd:anySimpleType" use="required" />
	</xsd:complexType>

	<xsd:attributeGroup name="idAttributes">
		<xsd:attribute name="id" type="xsd:string" use="required" />
		<xsd:attribute name="name" type="xsd:string" />
	</xsd:attributeGroup>
</xsd:schema>

=== feldob/InPUT/Java/Source/Tuning_Test/structuralSpace.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:DesignSpace id="structural" mapping="structuralSpaceMapping.xml" xmlns:i="http://TheInPUT.org/DesignSpace"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://TheInPUT.org/DesignSpace http://theinput.org/DesignSpace.xsd ">
	<i:SParam id="SomeStructural">
		<i:SChoice id="FirstChoice" />
		<i:SChoice id="SecondChoice" />
		<i:SChoice id="ThirdChoice" />
	</i:SParam>
	
	<i:SParam id="SomeStructuralParent" fixed="YetAnotherThirdChoice">
		<i:NParam id="SomeSharedPrimitiveSub" type="integer" fixed="3"/>
		<i:NParam id="AnotherSharedPrimitiveSub" type="long" fixed="30"/>
		<i:SChoice id="YetAnotherFirstChoice" />
		<i:SChoice id="YetAnotherSecondChoice" />
		<i:SChoice id="YetAnotherThirdChoice">
			<i:NParam id="SomeChoiceSpecificPrimitiveSub" type="float" />
		</i:SChoice>
		<i:SParam id="SomeSharedStructuralSub" type="String"/>
	</i:SParam>
</i:DesignSpace>

=== feldob/InPUT/Java/src/DocTest/boolParamSpace01.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:DesignSpace
    id="boolParamSpace01"
    xmlns:i="http://TheInPUT.org/DesignSpace"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://TheInPUT.org/DesignSpace http://theinput.org/DesignSpace.xsd" >

    <!--
        Checking the case sensitivity of boolean values.
        All these spellings are legal.
    -->

    <i:NParam type="boolean" id="A" fixed="True" />
    <i:NParam type="boolean" id="B" fixed="true" />
    <i:NParam type="boolean" id="C" fixed="TRUE" />
    <i:NParam type="boolean" id="D" fixed="tRUe" />

    <i:NParam type="boolean" id="Z" fixed="False" />
    <i:NParam type="boolean" id="Y" fixed="false" />
    <i:NParam type="boolean" id="X" fixed="FALSE" />
    <i:NParam type="boolean" id="W" fixed="fALESe" />

</i:DesignSpace>

=== feldob/InPUT/Java/src/DatabaseTransactionExamples/structuredSpaceAdvanced.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:DesignSpace id="structuredAdv" mapping="structuredMappingAdvanced.xml"
	xmlns:i="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://TheInPUT.org/DesignSpace http://TheInPUT.org/DesignSpace.xsd ">
	<i:SParam id="Steak">
		<i:NParam id="Temperature" type="decimal" inclMin="25" inclMax="80" />
		<i:NParam type="double" id="ProportionBurned" />
		<i:SChoice id="Raw">
			<i:NParam id="HealthRisk" type="boolean" />
		</i:SChoice>
		<i:SChoice id="Medium">
			<i:SParam id="Rather">
				<i:SChoice id="Raw" />
				<i:SChoice id="WellDone" />
			</i:SParam>
		</i:SChoice>
		<i:SChoice id="WellDone" />
	</i:SParam>
</i:DesignSpace>

=== feldob/InPUT/Java/src/DatabaseTransactionsExample/structuredSpaceBasic.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:DesignSpace id="structured" mapping="structuredMapping.xml" xmlns:i="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://TheInPUT.org/DesignSpace http://TheInPUT.org/DesignSpace.xsd ">
  <i:SParam id="Decision">
    <i:SChoice id="FirstChoice"/>
   <i:SChoice id="SecondChoice"/>
   <i:SChoice id="ThirdChoice"/>
  </i:SParam>
    <i:SParam id="AnotherDecision">
    <i:SChoice id="Raw"/>
   <i:SChoice id="Medium"/>
   <i:SChoice id="WellDone"/>
  </i:SParam>
</i:DesignSpace>

=== feldob/InPUT/Java/src/Tests/testSpace.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:DesignSpace id="testSpace" xmlns:i="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://TheInPUT.org/DesignSpace http://theinput.org/DesignSpace.xsd" mapping="testSpaceMapping.xml" >
	<i:NParam type="boolean" id="SomeBoolean" />
	<i:NParam type="integer" id="SomeInteger" />
	<i:NParam type="double" id="SomeDouble" />
	<i:NParam type="float" id="SomeFloat" />
	<i:NParam type="decimal" id="SomeDecimal" />
	<i:NParam type="short" id="SomeShort" />
	<i:NParam type="long" id="SomeLong" exclMin="0" />

	<i:NParam type="long" id="ABiggerLong" exclMin="SomeLong" />
	<i:NParam type="long" id="ASmallerLong" inclMax="Math.log(SomeLong)" />
	<i:NParam type="long" id="AStrangeLong"
		inclMin="SomeLong / ASmallerLong - ABiggerLong" />

	<i:NParam type="integer" id="SomeFixed" fixed="42" />

	<i:NParam type="integer[42]" id="SomeFixedArray" fixed="42" />

	<i:NParam type="integer[]" id="SomePrimitiveArrayOfUnspecifiedSize" />
	<i:NParam type="double[42]" id="SomePrimitiveArrayOfSpecifiedSize" />

	<i:NParam type="long[42][][42][]" id="SomeLargePrimitiveArray" />

	<i:NParam type="short" id="SomeRestrictedPrimitive" inclMin="-42"
		inclMax="42" />
	<i:NParam type="decimal" id="SomeVeryRestrictedPrimitive"
		exclMin="0.42222222222" exclMax="0.422222222221" />
	<i:NParam type="double" id="AnotherRestrictedPrimitive"
		exclMin="0.1,0.8" exclMax="0.4,0.9" />

	<i:NParam type="integer" id="OptionalNumeric" optional="true" />

	<i:SParam id="SomeStructural">
		<i:SChoice id="SomeFirstChoice" />
		<i:SChoice id="SomeSecondChoice" />
		<i:SChoice id="SomeThirdChoice" />
	</i:SParam>

	<i:SParam id="AnotherStructural">
		<i:SChoice id="AnotherFirstChoice" />
		<i:SChoice id="AnotherSecondChoice" />
		<i:SChoice id="AnotherThirdChoice" />
	</i:SParam>

	<i:SParam id="SomeStructuralParent">
		<i:NParam id="SomeSharedPrimitiveSub" type="integer" />
		<i:NParam id="AnotherSharedPrimitiveSub" type="long" />
		<i:SChoice id="YetAnotherFirstChoice" />
		<i:SChoice id="YetAnotherSecondChoice" />
		<i:SChoice id="YetAnotherThirdChoice">
			<i:NParam id="SomeChoiceSpecificPrimitiveSub" type="float" />
		</i:SChoice>
		<i:SParam id="SomeSharedStructuralSub" type="String"/>
	</i:SParam>

	<i:SParam id="AnotherStructuralParent" fixed="AndYetAnotherFirstChoice">
		<i:SParam id="SomeSharedStructuralSub">
			<i:SChoice id="SomeSubChoice" />
			<i:SChoice id="AnotherSubChoice" />
		</i:SParam>
		<i:SChoice id="AndYetAnotherFirstChoice" />
		<i:SChoice id="AndYetAnotherSecondChoice">
			<i:SParam id="SomeChoiceSpecificStructuralSub">
				<i:SChoice id="AlsoSingleChoicesAreValid" />
			</i:SParam>
		</i:SChoice>
	</i:SParam>

	<i:SParam id="SomeStringCustomizedByTheUser" type="String" />
	<i:SParam id="SomeStringArrayCustomizedByTheUser" type="String[10][5]" />

	<i:SParam id="AnotherStringCustomizedByTheUser" type="String">
		<i:SChoice id="someFile.xml" />
		<i:SChoice id="someFile.txt" />
		<i:SChoice id="anotherFile.xml" />
	</i:SParam>

	<i:SParam id="CustomizableInputDemonstrator">
		<i:NParam type="double" id="WrappedPrimitive" />
		<i:NParam type="double" id="CustomizableSetGetPrimitive" />
		<i:SChoice id="FirstChoice" />
		<i:SChoice id="SecondChoice" />
	</i:SParam>

	<i:SParam type="[][][]" id="SomeStructuralArrayOfUnspecifiedSize">
		<i:SChoice id="FirstChoice" />
		<i:SChoice id="SecondChoice" />
	</i:SParam>

	<i:SParam type="[3]" id="SomeComplexStructural" fixed="TheSecondSingleChoice TheSingleChoice">
		<i:SChoice id="TheSingleChoice"/>
		<i:SChoice id="TheSecondSingleChoice"/>
	</i:SParam>
	
	<i:SParam id="OptionalStructural" optional="true">
		<i:SChoice id="FirstChoice" />
		<i:SChoice id="SecondChoice" />
	</i:SParam>

</i:DesignSpace>

=== feldob/InPUT/Java/src/InPUT4j_Tuning/src/se/miun/itm/input/tuning/sequential/spot/spotSpace.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:DesignSpace id="spot" xmlns:i="http://TheInPUT.org/DesignSpace"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://TheInPUT.org/DesignSpace http://TheInput.org/DesignSpace.xsd ">
	<i:NParam id="spot.seed" type="long" />
	<i:NParam id="alg.seed" type="long" />
	<i:SParam id="init.design.func" type="String">
		<i:SChoice id="spotCreateDesignLhd" />
		<i:SChoice id="spotCreateDesignLhs" />
		<i:SChoice id="spotCreateDesignBasicDoe" />
		<i:SChoice id="spotCreateDesignDoeR3" />
		<i:SChoice id="spotCreateDesignFrF2" />
	</i:SParam>
	<i:NParam id="init.design.size" type="integer" inclMin="1" />
	<i:NParam id="init.design.retries" type="integer" inclMin="1" />
	<i:NParam id="init.design.repeats" type="integer" inclMin="1" />
	<i:NParam id="seq.design.size" type="integer" inclMin="1" />
	<i:NParam id="seq.design.retries" type="integer" inclMin="1" />
	<i:NParam id="seq.design.oldBest.size" type="integer" inclMin="0" />
	<i:NParam id="seq.design.new.size" type="integer" inclMin="1" />
	<i:NParam id="seq.design.maxRepeats" type="integer" inclMin="1" />
	<i:SParam id="seq.design.increase.func" type="String">
		<i:SChoice id="spotSeqDesignIncreasePlusOne" />
	</i:SParam>
	<i:SParam id="seq.design.func" type="String">
		<i:SChoice id="spotCreateDesignLhd" />
		<i:SChoice id="spotCreateDesignLhs" />
		<i:SChoice id="spotCreateDesignBasicDoe" />
		<i:SChoice id="spotCreateDesignDoeR3" />
		<i:SChoice id="spotCreateDesignFrF2" />
	</i:SParam>
	<i:SParam id="seq.predictionModel.func" type="String">
		<i:SChoice id="spotPredictDice" />
		<i:SChoice id="spotPredictEarth" />
		<i:SChoice id="spotPredictForrester" />
		<i:SChoice id="spotPredictGausspr" />
		<i:SChoice id="spotPredictDice" />
		<i:SChoice id="spotPredictKrig" />
		<i:SChoice id="spotPredictKsvm" />
		<i:SChoice id="spotPredictLm" />
		<i:SChoice id="spotPredictLmOptim" />
		<i:SChoice id="spotPredictMlegp" />
		<i:SChoice id="spotPredictOptMulti" />
		<i:SChoice id="spotPredictPsvm" />
		<i:SChoice id="spotPredictQrnn" />
		<i:SChoice id="spotPredictRandomForest" />
		<i:SChoice id="spotPredictRandomForestMlegp" />
		<i:SChoice id="spotPredictMlegp" />
		<i:SChoice id="spotPredictTgp" />
		<i:SChoice id="spotPredictTree" />
	</i:SParam>
	<i:SParam id="seq.merge.func" type="String">
		<i:SChoice id="mean" />
		<i:SChoice id="median" />
	</i:SParam>
	<i:SParam id="seq.transformation.func" type="String">
		<i:SChoice id="identity" />
		<i:SChoice id="log" />
		<i:SChoice id="inverse" /> <!-- for max problems! -->
	</i:SParam>
	<i:NParam id="seq.useAdaptiveRoi" type="boolean" />
	<i:NParam id="spot.ocba" type="boolean" />
<!-- 	<i:SParam id="report.func" type="String"> -->
<!-- 		<i:SChoice id="spotReportDefault"/> -->
<!-- 		<i:SChoice id="spotReport3d" /> -->
<!-- 		<i:SChoice id="" /> -->
<!-- 		<i:SChoice id="spotReportContour" /> -->
<!-- 		<i:SChoice id="spotReportMetaDefault" /> -->
<!-- 	</i:SParam> -->
	<i:NParam id="report.io.pdf" type="boolean" />
	<i:NParam id="spot.fileMode" type="boolean"/>
	<!-- <i:SParam id="seq.predictionOpt.func" type="String"> -->
	<!-- <i:SChoice id="spotCreateDesignLhs"/> -->
	<!-- </i:SParam> -->
		<!-- Extra setup for input -->
	<i:SParam id="spot.folder" type="String"/>
	<i:SParam id="alg.id" type="String"/>
</i:DesignSpace>

=== feldob/InPUT/Java/Source/PerformanceAnalyzerExample/poolInvestigationSpace.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:DesignSpace id="poolInvestigation" mapping="poolInvestigationMapping.xml"
	xmlns:i="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://TheInPUT.org/DesignSpace http://theinput.org/DesignSpace.xsd">
	<i:NParam id="amountTasks" type="integer" />
	<i:NParam id="executions" type="integer" />
	<i:NParam id="poolSize" type="integer[]" inclMin="1" inclMax="20" />
	<i:SParam id="task">
		<i:SChoice id="someJob">
			<i:NParam type="integer" id="firstValue" />
			<i:NParam type="integer" id="secondValue" />
			<i:SParam id="option">
				<i:SChoice id="some" />
			</i:SParam>
		</i:SChoice>
	</i:SParam>
</i:DesignSpace>

=== feldob/InPUT/Java/Source/Tuning_Test/combinedSpace.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:DesignSpace id="combined" mapping="combinedSpaceMapping.xml" xmlns:i="http://TheInPUT.org/DesignSpace"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://TheInPUT.org/DesignSpace http://theinput.org/DesignSpace.xsd ">

	<i:SParam id="SomeStructuralParent">
		<i:NParam id="SomeSharedPrimitiveSub" type="integer" fixed="3"/>
		<i:SChoice id="YetAnotherFirstChoice" />
		<i:SChoice id="YetAnotherSecondChoice" />
		<i:SChoice id="YetAnotherThirdChoice">
			<i:NParam id="SomeChoiceSpecificPrimitiveSub" type="float"/>
		</i:SChoice>
	</i:SParam>
		<i:SParam id="AnotherStructural">
		<i:SChoice id="AnotherFirstChoice" />
	</i:SParam>
		
	<i:SParam type="[3]" id="SomeComplexStructural" fixed="SecondChoice ...">
		<i:SChoice id="FirstChoice">
			<i:NParam id="A" type="float"/>
		</i:SChoice>
		<i:SChoice id="SecondChoice" />
	</i:SParam>
</i:DesignSpace>
