=== feldob/InPUT/DesignSpace.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Copyright (C) 2012 Felix Dobslaw$ Permission is hereby granted, free 
	of charge, to any person obtaining a copy of this software and associated 
	documentation files (the "Software"), to deal in the Software without restriction, 
	including without limitation the rights to use, copy, modify, merge, publish, 
	distribute, sublicense, and/or sell copies of the Software, and to permit 
	persons to whom the Software is furnished to do so, subject to the following 
	conditions: The above copyright notice and this permission notice shall be 
	included in all copies or substantial portions of the Software. THE SOFTWARE 
	IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
	BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
	PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS 
	BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
	OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH 
	THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. -->

<xsd:schema targetNamespace="http://TheInPUT.org/DesignSpace"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:i="http://TheInPUT.org/DesignSpace">

	<xsd:element name="DesignSpace" type="i:designSpaceType" />
	<xsd:complexType name="designSpaceType">
		<xsd:sequence>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="SChoiceType" type="i:structChoiceType" />
			</xsd:sequence>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:choice>
					<xsd:element name="SParam" type="i:complexParamType" />
					<xsd:element name="NParam" type="i:numericType" />
				</xsd:choice>
			</xsd:sequence>
		</xsd:sequence>
		<xsd:attributeGroup ref="i:idAttributes" />
		<xsd:attribute name="mapping" type="xsd:string" />
	</xsd:complexType>
	<xsd:complexType name="complexParamType">
		<xsd:sequence maxOccurs="1" minOccurs="1">
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:choice>
					<xsd:element name="SChoice" type="i:structChoiceType" />
					<xsd:element name="SParam" type="i:complexParamType" />
					<xsd:element name="NParam" type="i:numericType" />
				</xsd:choice>
			</xsd:sequence>
		</xsd:sequence>
		<xsd:attributeGroup ref="i:idAttributes" />
		<xsd:attribute name="type" type="xsd:string" />
		<xsd:attribute name="fixed" type="xsd:string" />
		<xsd:attribute name="optional" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="structChoiceType">
		<xsd:sequence>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:choice>
					<xsd:element name="SParam" type="i:complexParamType" />
					<xsd:element name="NParam" type="i:numericType" />
				</xsd:choice>
			</xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="type" type="xsd:string" />
		<xsd:attributeGroup ref="i:idAttributes" />
	</xsd:complexType>

	<xsd:complexType name="numericType">
		<xsd:attribute name="inclMin" type="xsd:anySimpleType" />
		<xsd:attribute name="exclMin" type="xsd:anySimpleType" />
		<xsd:attribute name="inclMax" type="xsd:anySimpleType" />
		<xsd:attribute name="exclMax" type="xsd:anySimpleType" />
		<xsd:attribute name="fixed" type="xsd:string" />
		<xsd:attributeGroup ref="i:idAttributes" />
		<xsd:attribute name="type" type="xsd:anySimpleType" use="required" />
	</xsd:complexType>

	<xsd:attributeGroup name="idAttributes">
		<xsd:attribute name="id" type="xsd:string" use="required" />
		<xsd:attribute name="name" type="xsd:string" />
	</xsd:attributeGroup>
</xsd:schema>

=== feldob/InPUT/Java/src/InPUT4j/src/se/miun/itm/input/configSpace.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:DesignSpace id="config" mapping="configMapping.xml" xmlns:i="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://TheInPUT.org/DesignSpace http://TheInPUT.org/DesignSpace.xsd ">
  <i:NParam id="threadSafe" type="boolean"/> <!-- not supported yet -->
  <i:NParam id="injection" type="boolean"/>
  <i:NParam id="logging" type="boolean"/>
  <i:SParam id="evaluator">
    <i:SChoice id="jeval"/>
    <i:SChoice id="javascript"/>
  </i:SParam>
  <i:SParam id="random">
	    <i:NParam id="seed" type="long"/>
	  	<i:SChoice id="standard"/>
	  	<i:SChoice id="mersenneTwister"/>
  </i:SParam>
  <i:NParam id="runtimeValidation" type="boolean"/>
  <i:SParam id="schemaPath" type="String"/>
  <i:NParam id="cacheDesigns" type="boolean"/>
</i:DesignSpace>

=== feldob/InPUT/Java/src/DocTest/circularDependencySpace04.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:DesignSpace
    id="circularDependencySpace04" xmlns:i="http://TheInPUT.org/DesignSpace"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://TheInPUT.org/DesignSpace http://TheInput.org/DesignSpace.xsd ">

    <!--
        These are the same parameters that are used in 02.
        We already know that no Design can be created using these parameters.
        However, while both 02 and 03 can be used to create a DesignSpace
        (only creating the Design fails), including both groups of parameters
        causes even the DesignSpace creation to fail.
    -->
    <i:NParam type="integer" id="C3" exclMin="A3"/>
    <i:NParam type="integer" id="B3" exclMin="C3"/>
    <i:NParam type="integer" id="A3" exclMin="B3"/>

    <!-- These are the same parameters as in 03. -->
    <i:NParam type="integer" id="A2" exclMax="B2"/>
    <i:NParam type="integer" id="B2" exclMin="C2"/>
    <i:NParam type="integer" id="C2" inclMax="D2"/>
    <i:NParam type="integer" id="D2" inclMin="A2"/>
    <!--
        Trying to create a DesignSpace using this file will cause a
        StackOverflowError.
        Param.dependsOn(Param) and Param.dependsOnDependers(Param) end up
        calling each other recursively.
    -->
</i:DesignSpace>
