=== feldob/InPUT/Design.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Copyright (C) 2012 Felix Dobslaw$ Permission is hereby granted, free 
	of charge, to any person obtaining a copy of this software and associated 
	documentation files (the "Software"), to deal in the Software without restriction, 
	including without limitation the rights to use, copy, modify, merge, publish, 
	distribute, sublicense, and/or sell copies of the Software, and to permit 
	persons to whom the Software is furnished to do so, subject to the following 
	conditions: The above copyright notice and this permission notice shall be 
	included in all copies or substantial portions of the Software. THE SOFTWARE 
	IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
	BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
	PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS 
	BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
	OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH 
	THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. -->

<xsd:schema targetNamespace="http://TheInPUT.org/Design"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:m="http://TheInPUT.org/DesignSpace" xmlns:i="http://TheInPUT.org/Design">
	<xsd:import namespace="http://TheInPUT.org/DesignSpace"
		schemaLocation="DesignSpace.xsd" />

	<xsd:element name="Design" type="i:designType" />

	<xsd:complexType name="designType">
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:choice>
				<xsd:element name="SValue" type="i:structType" />
				<xsd:element name="NValue" type="i:numericType" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attributeGroup ref="m:idAttributes" />
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="ref" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="structType">
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:choice>
				<xsd:element name="SValue" type="i:structType" />
				<xsd:element name="NValue" type="i:numericType" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attributeGroup ref="m:idAttributes" />
		<xsd:attribute name="value" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="numericType">
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:choice>
				<xsd:element name="NValue" type="i:numericType" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attributeGroup ref="m:idAttributes" />
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

</xsd:schema>

=== feldob/InPUT/Java/src/InPUT4j_Tuning/src/se/miun/itm/input/tuning/sequential/spot/spot.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:Design id="spotConfig" ref="spotSpace.xml" xmlns:i="http://TheInPUT.org/Design" xmlns:i1="http://TheInPUT.org/DesignSpace"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://TheInPUT.org/Design http://TheInput.org/Design.xsd ">
	<i:NValue id="spot.seed" value="125" />
	<i:NValue id="alg.seed" value="4321" />
	<i:SValue id="init.design.func" value="spotCreateDesignLhd" />
	<i:NValue id="init.design.size" value="4"/>
	<i:NValue id="init.design.retries" value="5"/>
	<i:NValue id="init.design.repeats" value="3"/>
	<i:NValue id="seq.design.size" value="200"/>
	<i:NValue id="seq.design.retries" value="10"/>
	<i:NValue id="seq.design.oldBest.size" value="1"/>
	<i:NValue id="seq.design.new.size" value="5"/>
	<i:NValue id="seq.design.maxRepeats" value="10"/>
	<i:SValue id="seq.design.increase.func" value="spotSeqDesignIncreasePlusOne"/>
	<i:SValue id="seq.design.func" value="spotCreateDesignLhd"/>
	<i:SValue id="seq.predictionModel.func" value="spotPredictForrester"/>
	<i:SValue id="seq.merge.func" value="mean"/>
	<i:SValue id="seq.transformation.func" value="inverse"/>
	<i:NValue id="seq.useAdaptiveRoi" value="false" />
	<i:NValue id="spot.ocba" value="true" />
<!-- 	<i:SValue id="report.func" value="spotReportDefault"/> -->
	<i:NValue id="report.io.pdf" value="true" />
	<i:NValue id="spot.fileMode" value="true"/>
	<!-- <i:SValue id="seq.predictionOpt.func" value="?"> -->
		<!-- Extra setup for input -->
	<i:SValue id="spot.folder" value="experiment"/>
	<i:SValue id="alg.id" value="input"/>
</i:Design>

=== feldob/InPUT/Java/Source/Injection_Examples/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<in:Design ref="someSpace.xml" xmlns:in="http://TheInPUT.org/Design" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://TheInPUT.org/Design http://TheInPUT.org/Design.xsd" id="1">
  <in:NValue id="paramId">
    <in:NValue id="1" value="188912922" />
    <in:NValue id="2" value="-1772388034" />
    <in:NValue id="3" value="-84875878" />
    <in:NValue id="4" value="-2072655376" />
    <in:NValue id="5" value="-1895759550" />
    <in:NValue id="6" value="-208226690" />
    <in:NValue id="7" value="341253300" />
    <in:NValue id="8" value="-1327618916" />
    <in:NValue id="9" value="1826954414" />
    <in:NValue id="10" value="-2126595010" />
  </in:NValue>
</in:Design>

=== feldob/InPUT/Java/Source/PerformanceAnalyzerExample/performance.xml
<?xml version="1.0" encoding="UTF-8"?>
<in:Design xmlns:in="http://TheInPUT.org/Design" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://TheInPUT.org/Design http://TheInPUT.org/Design.xsd" id="1356274766327" ref="performanceSpace">
  <in:NValue id="performance">
    <in:NValue id="1">
      <in:NValue id="1" value="2544" />
      <in:NValue id="2" value="1808" />
      <in:NValue id="3" value="2501" />
    </in:NValue>
    <in:NValue id="2">
      <in:NValue id="1" value="1263" />
      <in:NValue id="2" value="1154" />
      <in:NValue id="3" value="1041" />
    </in:NValue>
    <in:NValue id="3">
      <in:NValue id="1" value="1357" />
      <in:NValue id="2" value="1124" />
      <in:NValue id="3" value="1585" />
    </in:NValue>
    <in:NValue id="4">
      <in:NValue id="1" value="1513" />
      <in:NValue id="2" value="1280" />
      <in:NValue id="3" value="1215" />
    </in:NValue>
    <in:NValue id="5">
      <in:NValue id="1" value="1026" />
      <in:NValue id="2" value="1051" />
      <in:NValue id="3" value="1115" />
    </in:NValue>
  </in:NValue>
</in:Design>
<!--Sat Apr 13 15:40:10 CEST 2013
Environment: Language="java" Version="1.7.0" Architecture="amd64" Processors="2" OS="Linux" Memory="124125184"-->

=== feldob/InPUT/Java/Source/StackoverflowExample/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:Design id="someConfig" ref="configSpace.xml" xmlns:i="http://TheInPUT.org/Design" xmlns:i1="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://TheInPUT.org/Design http://TheInPUT.org/Design.xsd ">
<i:SValue id="ListCreator">
	<i:SValue id="1">
		<i:NValue id="SortDescending" value="true"/>
		<i:SValue id="TableWriter" value="Pdf"/>
	</i:SValue>
	<i:SValue id="2">
		<i:NValue id="SortDescending" value="false"/>
		<i:SValue id="TableWriter" value="Xls"/>
	</i:SValue>
</i:SValue>
</i:Design>

=== feldob/InPUT/Java/src/InPUT4j/src/se/miun/itm/input/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:Design id="config" xmlns:i="http://TheInPUT.org/Design" xmlns:i1="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://TheInPUT.org/Design http://TheInPUT.org/Design.xsd ">
  <i:SValue id="evaluator" value="javascript"/>
  <i:SValue id="random" value="mersenneTwister">
    <i:NValue id="seed" value="123456789"/>
  </i:SValue>
  <i:NValue id="threadSafe" value="false"/><!-- not supported yet -->
  <i:NValue id="logging" value="false"/>
  <i:NValue id="injection" value="true"/>
  <i:NValue id="runtimeValidation" value="false"/>
  <i:SValue id="schemaPath" value="http://TheInPUT.org/"/>
  <i:NValue id="cacheDesigns" value="false"/>
</i:Design>

=== feldob/InPUT/Java/Source/PerformanceAnalyzerExample/poolInvestigation.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:Design id="investigation1" ref="poolInvestigationSpace.xml" xmlns:i="http://TheInPUT.org/Design"
	xmlns:i1="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://TheInPUT.org/Design http://theinput.org/Design.xsd ">
	<i:NValue id="amountTasks" value="10" />
	<i:NValue id="executions" value="3" />
	<i:NValue id="poolSize">
		<i:NValue id="1" value="1" />
		<i:NValue id="2" value="2" />
		<i:NValue id="3" value="8" />
		<i:NValue id="4" value="9" />
		<i:NValue id="5" value="10" />
	</i:NValue>
	<i:SValue id="task" value="someJob">
		<i:NValue id="firstValue" value="100000000"/>
		<i:NValue id="secondValue" value="4000000"/>
		<i:SValue id="option" value="some"/>
	</i:SValue>
</i:Design>
